---
version: "3.1"
services:
  cust-image:
    container_name: custom-image
    image: "pakomp/helloapp:v1"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped